# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1463562092);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1463562212);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1463561732);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1463561972);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1463561852);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/vijay/Videos");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.blocked", "{\"fRJBBzcD6JqRhIExq3tA/g==\":1,\"X03UnDX6s8EM6vD6GlzmUg==\":1,\"1/V7l0tAbDaGPyRpP3F3kg==\":1,\"QZtYQmGoNyQdLVv6+l3Epw==\":1,\"7/ShUSkUYtrNrI6Z5nfLrQ==\":1,\"1BJ7TKg3/Uw7LbuELwlEbg==\":1,\"up8Jf4y1mHiQ89dTPi2+xA==\":1,\"hPdLJ6uXOM1ZAzxqyEvaNQ==\":1,\"3D/zfMIZD64YgGd98KI7hQ==\":1,\"xssMPG761x4nUYHo9RNgxQ==\":1,\"ISLFZW2j2G13wI969IwCaA==\":1,\"dD1EvVHh/owIjz5y6KnGig==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140715215003");
user_pref("browser.slowStartup.averageTime", 6775);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20140715215003");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1463033627233");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1463561675930");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1463561684155");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1463648084155");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1462417098346");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1462445297061");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-button-pressed");
user_pref("datareporting.policy.firstRunTime", "1454858987072");
user_pref("datareporting.sessions.current.activeTicks", 81);
user_pref("datareporting.sessions.current.firstPaint", 6237);
user_pref("datareporting.sessions.current.main", 1913);
user_pref("datareporting.sessions.current.sessionRestored", 8124);
user_pref("datareporting.sessions.current.startTime", "1463561608310");
user_pref("datareporting.sessions.current.totalTime", 663);
user_pref("datareporting.sessions.currentIndex", 160);
user_pref("datareporting.sessions.prunedIndex", 159);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 37);
user_pref("extensions.blocklist.pingCountVersion", 37);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"31.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"31.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150311.01");
user_pref("extensions.html5rend.7252482ef4a6c3a848f512f3bf7b29c7", 1638575360);
user_pref("extensions.html5rend.806e0f58aa3f837b872ebca34f54a7df", 1623077360);
user_pref("extensions.html5rend.d41d8cd98f00b204e9800998ecf8427e", 0);
user_pref("extensions.html5rend.last_running", 0);
user_pref("extensions.html5rend.uuid", "f2fe849f-8154-4b25-a820-f71c59855fb7");
user_pref("extensions.html5rend.version", 3);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1407427487000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1407427324000,\"rdfTime\":1405462250000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1405463632000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1405463632000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140715215003");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1463562324);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1463561676);
user_pref("places.history.expiration.transient_current_max_pages", 45764);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("spellchecker.dictionary", "en_US");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1462159101);
user_pref("toolkit.startup.last_success", 1463561610);
user_pref("toolkit.telemetry.previousBuildID", "20140715215003");
