# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a31431057f2083c77b259b62b54fcdeb1ee6aa85cf78e995a61878da60238bf8b43334db6e8cbef45a08218c63a04ed1011037d416a458402598ac65f3915405

test:
  secret_key_base: bdbcaa85ddae7365cf8f6e45a17c04c3c4f4e7067e2a9768e19e596b406c4de62577a9cf2146c4a361db1c10725495d2725cc02c6489038176b1e052e01fe583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
